session_name: '${DEV_NAME} dev'
start_directory: '${HOME}/mine/repos/${DEV_NAME}'
windows:
  - window_name: 'files'
    panes:
      - shell_command: 'g st'
  - window_name: 'edit'
    panes:
      - shell_command: '$EDITOR'
  - window_name: 'build'
    panes:
      - 'blank'
  - window_name: 'run'
    panes:
      - 'blank'
