# default config found at /etc/xdg/fuzzel/fuzzel.ini

font=SeriousShanns Nerd Font Mono:size=16,Source Sans Pro:size=16,monospace
use-bold=yes
prompt=":) "
exit-on-keyboard-focus-loss=yes
placeholder=" test placeholder "

# list-executables-in-path=no

[colors]
background=888888ff
text=303030ff
input=303030ff
prompt=a05614ff
placeholder=bbbbbbff
border=700000ff
match=700000ff
selection-match=700000ff
selection=606060ff
selection-text=303030ff
# counter=93a1a1ff

[border]
width=5
radius=10

[dmenu]
# mode=text  # text|index
# exit-immediately-if-empty=no
