[general]
import = ["~/.config/alacritty/base-alacritty.toml"]

[font]
size = 11.0
glyph_offset = { x = 0, y = -2 } # for SeriousShanns

[font.normal]
family = "SeriousShanns Nerd Font Mono"

[window]
opacity = 1

[colors]
transparent_background_colors = true
