# this configuration expects two environment variables to be set:
# - DEV_NAME
# - DEV_DIR
session_name: '${DEV_NAME} dev'
start_directory: '${DEV_DIR}'
windows:
  - window_name: 'files'
    panes:
      - shell_command: 'git-dash'
  - window_name: 'edit'
    panes:
      - shell_command: '$EDITOR'
  - window_name: 'build'
    panes:
      - 'blank'
  - window_name: 'run'
    panes:
      - 'blank'
