name: jdtls
flavor: web-fetch
web-url: https://download.eclipse.org/jdtls/milestones/%VERSION%/jdt-language-server-%VERSION%-%TIMESTAMP_VERSION%.tar.gz
version: 1.43.0
build-action: script
build-target: bin/jdtls
build-cmd: tar -xzf jdt-language-server-%VERSION%-%TIMESTAMP_VERSION%.tar.gz
keep-bin-with-source: true
misc-vars:
  TIMESTAMP_VERSION: '202412191447'
