[general]
import = ["~/.config/alacritty/base-alacritty.toml"]

[font]
# bump up size to make font rendering on MacOS look less terrible
size = 16.5
offset = { x = 0, y = 3  }

[font.normal]
family = "SeriousShanns Nerd Font Mono"

[window]
# Make left `Option` key behave as `Alt` (macOS only)
option_as_alt = "OnlyLeft"
